"""created stock_details join table

Revision ID: c4c0e20b4879
Revises: 49ee00afc1c5
Create Date: 2021-03-30 14:03:54.246804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c0e20b4879'
down_revision = '49ee00afc1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock__details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_bought', sa.Date(), nullable=False),
    sa.Column('buy_price', sa.Float(), nullable=False),
    sa.Column('num_of_shares', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock__details')
    # ### end Alembic commands ###
