"""created stocks table

Revision ID: 49ee00afc1c5
Revises: 998020e7ee14
Create Date: 2021-03-30 13:02:10.346381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ee00afc1c5'
down_revision = '998020e7ee14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('stock_ticker', sa.String(length=20), nullable=False),
    sa.Column('company_info', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_info'),
    sa.UniqueConstraint('company_name'),
    sa.UniqueConstraint('stock_ticker')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks')
    # ### end Alembic commands ###
