"""adding banking_details

Revision ID: e419e8244527
Revises: 34d844a2afb7
Create Date: 2021-04-23 00:59:47.340797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e419e8244527'
down_revision = '34d844a2afb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banking_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=300), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banking_details')
    # ### end Alembic commands ###
