"""updating stock table

Revision ID: 34d844a2afb7
Revises: c4c0e20b4879
Create Date: 2021-04-14 18:47:54.702952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d844a2afb7'
down_revision = 'c4c0e20b4879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('dividend_yield', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('market_cap', sa.BigInteger(), nullable=False))
    op.add_column('stocks', sa.Column('num_employees', sa.Integer(), nullable=False))
    op.add_column('stocks', sa.Column('pe_ratio', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'pe_ratio')
    op.drop_column('stocks', 'num_employees')
    op.drop_column('stocks', 'market_cap')
    op.drop_column('stocks', 'dividend_yield')
    # ### end Alembic commands ###
