"""update banking_details table

Revision ID: 13981a058d20
Revises: e419e8244527
Create Date: 2021-05-13 20:57:40.230333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13981a058d20'
down_revision = 'e419e8244527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banking_details', sa.Column('account_type', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banking_details', 'account_type')
    # ### end Alembic commands ###
